Fix workflow bug, add TMRT permanent message

diff --git a/.github/workflows/check_and_deploy.yml b/.github/workflows/check_and_deploy.yml
--- a/.github/workflows/check_and_deploy.yml
+++ b/.github/workflows/check_and_deploy.yml
@@ -50,7 +50,8 @@ jobs:
         run: |
           content=`cat ./disruptions.json`
           echo "::set-output name=payload::$content"
-      - name: Invoke Lambda
+      - name: Invoke AWS Lambda
+        id: invoke_aws_lambda
         uses: gagoar/invoke-aws-lambda@master
         with:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -58,5 +59,13 @@ jobs:
           REGION: ${{ secrets.AWS_REGION }}
           FunctionName: ttwCustomDisruptionCollector
           Payload: ${{ steps.create_payload.outputs.payload }}
-      - name: Store response payload to file
-        run: echo '${{ fromJSON(steps.foobar.outputs.response).Payload }}' > invocation-response.json
+      - name: AWS Lambda response success
+        if: ${{ fromJSON(steps.invoke_aws_lambda.outputs.response).StatusCode == 200 }}
+        run: |
+          echo "AWS Lambda response ${{ steps.invoke_aws_lambda.outputs.response }} Success!"
+      - name: AWS Lambda response failure
+        if: ${{ fromJSON(steps.invoke_aws_lambda.outputs.response).StatusCode != 200 }}
+        run: |
+          echo "AWS Lambda response ${{ steps.invoke_aws_lambda.outputs.response }} Failure!"
+          echo "Error: ${{ fromJSON(steps.invoke_aws_lambda.outputs.response).body }}"
+          exit 1
